- name: deploy apache
  hosts: web
  become: yes
  tasks :
  - name: install apache
    yum :
      name: httpd
      state: present
  - name: install unzip 
    yum:
      name: unzip
      state: present
  - name: send the zip to remote server
    copy:
      src: flamix-build.zip
      dest: /tmp/
  - name: unzip the file in remote server
    unarchive:
      src: /tmp/flamix-build.zip
      dest: /var/www/html/
      remote_src: yes

  - name: start service
    service:  
      name: httpd
      state: restarted
  - name: enable service
    service:
      name: httpd
      enabled: yes

    


