- name: deploy apache
  hosts: web
  become: yes
  tasks :
  - name: install apache
    yum :
      name: httpd
      state: present
  - name: start service
    service:  
      name: httpd
      state: started
  - name: enable service
    service:
      name: httpd
      enabled: yes

         
